ar_layers: &id001 []
compute_components_flag: false
config_ar: !!python/object:neuralprophet.configure.AR
  ar_layers: *id001
  ar_reg: null
  n_lags: 24
  reg_lambda: null
config_events: null
config_holidays: null
config_lagged_regressors: null
config_normalization: !!python/object:neuralprophet.configure.Normalization
  global_data_params: !!python/object/apply:collections.OrderedDict
  - - - ds
      - !!python/object:neuralprophet.df_utils.ShiftScale
        scale: !!python/object/apply:pandas._libs.tslibs.timedeltas._timedelta_unpickle
        - 1548000000000000
        - 10
        shift: !!python/object/apply:pandas._libs.tslibs.timestamps._unpickle_timestamp
        - 1765731600000000000
        - null
        - null
        - 10
    - - y
      - !!python/object:neuralprophet.df_utils.ShiftScale
        scale: !!python/object/apply:numpy.core.multiarray.scalar
        - &id002 !!python/object/apply:numpy.dtype
          args:
          - f8
          - false
          - true
          state: !!python/tuple
          - 3
          - <
          - null
          - null
          - null
          - -1
          - -1
          - 0
        - !!binary |
          AAAAAABgVkA=
        shift: !!python/object/apply:numpy.core.multiarray.scalar
        - *id002
        - !!binary |
          AAAAAAAAJUA=
  global_normalization: false
  global_time_normalization: true
  local_data_params: !!python/object/apply:collections.OrderedDict
  - - - E-commerce & Shopping
      - !!python/object/apply:collections.OrderedDict
        - - - ds
            - !!python/object:neuralprophet.df_utils.ShiftScale
              scale: !!python/object/apply:pandas._libs.tslibs.timedeltas._timedelta_unpickle
              - 1483200000000000
              - 10
              shift: !!python/object/apply:pandas._libs.tslibs.timestamps._unpickle_timestamp
              - 1765796400000000000
              - null
              - null
              - 10
          - - y
            - !!python/object:neuralprophet.df_utils.ShiftScale
              scale: !!python/object/apply:numpy.core.multiarray.scalar
              - *id002
              - !!binary |
                ZmZmZmZWUEA=
              shift: !!python/object/apply:numpy.core.multiarray.scalar
              - *id002
              - !!binary |
                ZmZmZmZmMEA=
    - - Education & Career
      - !!python/object/apply:collections.OrderedDict
        - - - ds
            - !!python/object:neuralprophet.df_utils.ShiftScale
              scale: !!python/object/apply:pandas._libs.tslibs.timedeltas._timedelta_unpickle
              - 1476000000000000
              - 10
              shift: !!python/object/apply:pandas._libs.tslibs.timestamps._unpickle_timestamp
              - 1765803600000000000
              - null
              - null
              - 10
          - - y
            - !!python/object:neuralprophet.df_utils.ShiftScale
              scale: !!python/object/apply:numpy.core.multiarray.scalar
              - *id002
              - !!binary |
                AAAAAADAVUA=
              shift: !!python/object/apply:numpy.core.multiarray.scalar
              - *id002
              - !!binary |
                AAAAAAAAKkA=
    - - Entertainment
      - !!python/object/apply:collections.OrderedDict
        - - - ds
            - !!python/object:neuralprophet.df_utils.ShiftScale
              scale: !!python/object/apply:pandas._libs.tslibs.timedeltas._timedelta_unpickle
              - 1483200000000000
              - 10
              shift: !!python/object/apply:pandas._libs.tslibs.timestamps._unpickle_timestamp
              - 1765796400000000000
              - null
              - null
              - 10
          - - y
            - !!python/object:neuralprophet.df_utils.ShiftScale
              scale: !!python/object/apply:numpy.core.multiarray.scalar
              - *id002
              - !!binary |
                ZmZmZmYGTEA=
              shift: !!python/object/apply:numpy.core.multiarray.scalar
              - *id002
              - !!binary |
                MzMzMzMzPUA=
    - - Fashion & Beauty
      - !!python/object/apply:collections.OrderedDict
        - - - ds
            - !!python/object:neuralprophet.df_utils.ShiftScale
              scale: !!python/object/apply:pandas._libs.tslibs.timedeltas._timedelta_unpickle
              - 1548000000000000
              - 10
              shift: !!python/object/apply:pandas._libs.tslibs.timestamps._unpickle_timestamp
              - 1765731600000000000
              - null
              - null
              - 10
          - - y
            - !!python/object:neuralprophet.df_utils.ShiftScale
              scale: !!python/object/apply:numpy.core.multiarray.scalar
              - *id002
              - !!binary |
                mpmZmZk5UUA=
              shift: !!python/object/apply:numpy.core.multiarray.scalar
              - *id002
              - !!binary |
                mpmZmZmZOEA=
    - - Finance & Investment
      - !!python/object/apply:collections.OrderedDict
        - - - ds
            - !!python/object:neuralprophet.df_utils.ShiftScale
              scale: !!python/object/apply:pandas._libs.tslibs.timedeltas._timedelta_unpickle
              - 1479600000000000
              - 10
              shift: !!python/object/apply:pandas._libs.tslibs.timestamps._unpickle_timestamp
              - 1765800000000000000
              - null
              - null
              - 10
          - - y
            - !!python/object:neuralprophet.df_utils.ShiftScale
              scale: !!python/object/apply:numpy.core.multiarray.scalar
              - *id002
              - !!binary |
                AAAAAAAwUEA=
              shift: !!python/object/apply:numpy.core.multiarray.scalar
              - *id002
              - !!binary |
                AAAAAACgQUA=
    - - Food & Culinary
      - !!python/object/apply:collections.OrderedDict
        - - - ds
            - !!python/object:neuralprophet.df_utils.ShiftScale
              scale: !!python/object/apply:pandas._libs.tslibs.timedeltas._timedelta_unpickle
              - 1486800000000000
              - 10
              shift: !!python/object/apply:pandas._libs.tslibs.timestamps._unpickle_timestamp
              - 1765792800000000000
              - null
              - null
              - 10
          - - y
            - !!python/object:neuralprophet.df_utils.ShiftScale
              scale: !!python/object/apply:numpy.core.multiarray.scalar
              - *id002
              - !!binary |
                ZmZmZmbmTUA=
              shift: !!python/object/apply:numpy.core.multiarray.scalar
              - *id002
              - !!binary |
                MzMzMzMzM0A=
    - - Gaming & Esports
      - !!python/object/apply:collections.OrderedDict
        - - - ds
            - !!python/object:neuralprophet.df_utils.ShiftScale
              scale: !!python/object/apply:pandas._libs.tslibs.timedeltas._timedelta_unpickle
              - 212400000000000
              - 10
              shift: !!python/object/apply:pandas._libs.tslibs.timestamps._unpickle_timestamp
              - 1767067200000000000
              - null
              - null
              - 10
          - - y
            - !!python/object:neuralprophet.df_utils.ShiftScale
              scale: !!python/object/apply:numpy.core.multiarray.scalar
              - *id002
              - !!binary |
                AAAAAABgUUA=
              shift: !!python/object/apply:numpy.core.multiarray.scalar
              - *id002
              - !!binary |
                AAAAAAAALUA=
    - - Health & Fitness
      - !!python/object/apply:collections.OrderedDict
        - - - ds
            - !!python/object:neuralprophet.df_utils.ShiftScale
              scale: !!python/object/apply:pandas._libs.tslibs.timedeltas._timedelta_unpickle
              - 1479600000000000
              - 10
              shift: !!python/object/apply:pandas._libs.tslibs.timestamps._unpickle_timestamp
              - 1765800000000000000
              - null
              - null
              - 10
          - - y
            - !!python/object:neuralprophet.df_utils.ShiftScale
              scale: !!python/object/apply:numpy.core.multiarray.scalar
              - *id002
              - !!binary |
                ZmZmZmbmUEA=
              shift: !!python/object/apply:numpy.core.multiarray.scalar
              - *id002
              - !!binary |
                ZmZmZmZmNkA=
    - - Technology & Gadgets
      - !!python/object/apply:collections.OrderedDict
        - - - ds
            - !!python/object:neuralprophet.df_utils.ShiftScale
              scale: !!python/object/apply:pandas._libs.tslibs.timedeltas._timedelta_unpickle
              - 1483200000000000
              - 10
              shift: !!python/object/apply:pandas._libs.tslibs.timestamps._unpickle_timestamp
              - 1765796400000000000
              - null
              - null
              - 10
          - - y
            - !!python/object:neuralprophet.df_utils.ShiftScale
              scale: !!python/object/apply:numpy.core.multiarray.scalar
              - *id002
              - !!binary |
                AAAAAABgUkA=
              shift: !!python/object/apply:numpy.core.multiarray.scalar
              - *id002
              - !!binary |
                AAAAAAAAJUA=
    - - Travel & Tourism
      - !!python/object/apply:collections.OrderedDict
        - - - ds
            - !!python/object:neuralprophet.df_utils.ShiftScale
              scale: !!python/object/apply:pandas._libs.tslibs.timedeltas._timedelta_unpickle
              - 1479600000000000
              - 10
              shift: !!python/object/apply:pandas._libs.tslibs.timestamps._unpickle_timestamp
              - 1765800000000000000
              - null
              - null
              - 10
          - - y
            - !!python/object:neuralprophet.df_utils.ShiftScale
              scale: !!python/object/apply:numpy.core.multiarray.scalar
              - *id002
              - !!binary |
                zMzMzMyMUUA=
              shift: !!python/object/apply:numpy.core.multiarray.scalar
              - *id002
              - !!binary |
                zczMzMzMKEA=
  normalize: minmax
  unknown_data_normalization: false
config_regressors: !!python/object:neuralprophet.configure.ConfigFutureRegressors
  d_hidden: 4
  model: linear
  num_hidden_layers: 2
  regressors: null
config_seasonality: !!python/object:neuralprophet.configure.ConfigSeasonality
  computation: fourier
  condition_name: null
  daily_arg: true
  daily_global_local: auto
  global_local: global
  mode: additive
  periods: !!python/object/apply:collections.OrderedDict
  - - - weekly
      - !!python/object:neuralprophet.configure.Season
        arg: true
        condition_name: null
        global_local: global
        period: 7
        resolution: 3
    - - daily
      - !!python/object:neuralprophet.configure.Season
        arg: true
        condition_name: null
        global_local: global
        period: 1
        resolution: 6
  reg_lambda: 0
  seasonality_local_reg: false
  weekly_arg: true
  weekly_global_local: auto
  yearly_arg: false
  yearly_global_local: auto
config_train: !!python/object:neuralprophet.configure.Train
  batch_size: 64
  epochs: 50
  lambda_delay: 25
  learning_rate: 0.0001
  loss_func: !!python/object:torch.nn.modules.loss.SmoothL1Loss
    _backward_hooks: !!python/object/apply:collections.OrderedDict
    - []
    _backward_pre_hooks: !!python/object/apply:collections.OrderedDict
    - []
    _buffers: !!python/object/apply:collections.OrderedDict
    - []
    _forward_hooks: !!python/object/apply:collections.OrderedDict
    - []
    _forward_hooks_always_called: !!python/object/apply:collections.OrderedDict
    - []
    _forward_hooks_with_kwargs: !!python/object/apply:collections.OrderedDict
    - []
    _forward_pre_hooks: !!python/object/apply:collections.OrderedDict
    - []
    _forward_pre_hooks_with_kwargs: !!python/object/apply:collections.OrderedDict
    - []
    _is_full_backward_hook: null
    _load_state_dict_post_hooks: !!python/object/apply:collections.OrderedDict
    - []
    _load_state_dict_pre_hooks: !!python/object/apply:collections.OrderedDict
    - []
    _modules: !!python/object/apply:collections.OrderedDict
    - []
    _non_persistent_buffers_set: !!set {}
    _parameters: !!python/object/apply:collections.OrderedDict
    - []
    _state_dict_hooks: !!python/object/apply:collections.OrderedDict
    - []
    _state_dict_pre_hooks: !!python/object/apply:collections.OrderedDict
    - []
    beta: 0.3
    reduction: none
    training: true
  loss_func_name: SmoothL1Loss
  lr_finder_args: {}
  n_data: 2441
  newer_samples_start: 0.0
  newer_samples_weight: 2
  optimizer: !!python/name:torch.optim.adamw.AdamW ''
  optimizer_args:
    weight_decay: 0.001
  quantiles:
  - 0.5
  reg_delay_pct: 0.5
  reg_lambda_trend: null
  scheduler: !!python/name:torch.optim.lr_scheduler.OneCycleLR ''
  scheduler_args:
    anneal_strategy: cos
    div_factor: 10.0
    final_div_factor: 10.0
    pct_start: 0.3
    three_phase: true
  trend_reg_threshold: null
config_trend: !!python/object:neuralprophet.configure.Trend
  changepoints: null
  changepoints_range: 0.8
  growth: linear
  n_changepoints: 10
  trend_global_local: global
  trend_local_reg: false
  trend_reg: 0
  trend_reg_threshold: null
id_list:
- E-commerce & Shopping
- Education & Career
- Entertainment
- Fashion & Beauty
- Finance & Investment
- Food & Culinary
- Gaming & Esports
- Health & Fitness
- Technology & Gadgets
- Travel & Tourism
lagged_reg_layers: []
max_lags: 24
meta_used_in_model: false
metrics:
  MAE:
  - MeanAbsoluteError
  - {}
  RMSE:
  - MeanSquaredError
  - squared: false
n_forecasts: 24
n_lags: 24
num_seasonalities_modelled: 1
num_seasonalities_modelled_dict: !!python/object/apply:collections.OrderedDict
- - - yearly
    - 1
  - - weekly
    - 1
  - - daily
    - 1
num_trends_modelled: 1
